version: '3'

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABSE: Lazhopee
  test-db:
    image:  mongo
    restart: always 
    ports:
      - "27019:27017"
    environment:
      MONGODB_DATABSE: TestLazhopee
      